kuzzleio/kuzzle-proxy

lib/service/Broker.js, lib/service/Server.js
Instead of replaying each request when a server die, send an error to clients.
This was to carry about sensible requests (like create documents, or other things in the persisted data layer) and let final user to implement his own logic.
=> add request rejection if the corresponding server die

lib/service/Broker.js, test/service/broker.test.js
Bug fix: When calling [http.server.listen](https://nodejs.org/api/http.html#http_server_listen_handle_callback) multiple times, the server is re-opened but the previously registered callbacks are still registered.
=> 26 27 networkoptions and plugins install

lib/service/HttpProxy.js, test/service/httpProxy.test.js
Allow clients to perform HTTP OPTIONS requests, for instance as a preflight request for subsequent AJAX calls.
=> Add support for HTTP OPTIONS requests

lib/service/HttpProxy.js, package.json, test/service/httpProxy.test.js
:warning: needs https://github.com/kuzzleio/kuzzle-common-objects/pull/11 to be merged first.
fixes #37
This PR adds the ability to send some custom HTTP headers from Kuzzle (and most importantly, from a plugin).
The sad downside is that to do so, we have to JSON parse the response from Kuzzle :\
=> fixes #37 - Add support for http headers

lib/service/HttpProxy.js, package.json, test/service/httpProxy.test.js
Following [previous merge of this branch](#38), @dbengsch noticed the JSON parsing could actually be removed by making Kuzzle send the response as an object.
:warning: both this pr and [its related one on Kuzzle](https://github.com/kuzzleio/kuzzle/pull/575) need to be merged at the same time.
=> Response headers handling - remove double JSON stringification

.proxyrc.sample, lib/core/config.js, lib/service/HttpProxy.js, package.json, test/service/backend.test.js, test/service/httpProxy.test.js
Requires:
* https://github.com/kuzzleio/kuzzle-common-objects/pull/13
* https://github.com/kuzzleio/kuzzle-plugin-socketio/pull/13
* https://github.com/kuzzleio/kuzzle-plugin-websocket/pull/11
Fix: https://github.com/kuzzleio/kuzzle/issues/586
* The configuration property `accessControlAllowOrigin`, setting the HTTP `Access-Control-Allow-Origin` header, has been moved to the Kuzzle core project
* HTTP OPTIONS requests are no longer handled by the proxy. These are now forwarded to Kuzzle like any other request
* handle the new Kuzzle response format, including the raw response content for HTTP
=> Kuzzle #586: dynamic http options

lib/core/Context.js, lib/core/KuzzleProxy.js, lib/core/clientConnection.js, lib/core/config.js, lib/service/Backend.js, lib/service/Broker.js, lib/service/HttpProxy.js, lib/service/Router.js, lib/store/ClientConnection.js, package.json, test/core/clientConnection.test.js, test/core/context.test.js, test/core/kuzzleProxy.test.js, test/service/backend.test.js, test/service/broker.test.js, test/service/httpProxy.test.js, test/service/router.test.js, test/store/clientConnection.test.js
cf #39 
* 2 loggers ([winston](https://github.com/winstonjs/winston)) are injected in the Proxy, each having its own configuration:
1. One dedicated to access logs
2. One dedicated to other (errors) logs
* All `console.log` and `console.error` calls are removed and use the error logger instead.
* Default configuration is to output logs to the terminal. Access logs are sent to stdout, ~~error logs are sent to stderr.~~ [EDIT: error logs levels `warn`, `error` and `debug` are sent to stderr, other levels are output to stdout.]
* Currently supported transports are `console`, `file`, `elasticsearch` and `syslog`.
For the time being, 2 output formats are supported: `logstash` and `combined`. 
The `logstash` format outputs the data in json, ready to use by logstash (or by elasticsearch …
=> Access logs

.proxyrc.sample, lib/core/config.js, lib/service/HttpFormDataStream.js, lib/service/HttpProxy.js, package.json, test/service/httpProxy.test.js
Add the capability to support both `application/x-www-form-urlencoded` and `multpart/form-data` content-types for HTTP requests.
This will enable clients to upload files through HTTP.
All incoming messages are turned into JSON data, to let Kuzzle core always manage JSON inputs.
Binary files are base64-encoded and encapsuled within following sample request format:
```json
{
"requestId": "bbbebe25-7d6a-4079-b9a8-5f7b3c544094",
"url": "/foo/bar/baz",
"method": "PUT",
"headers":  {
"host": "kuzzle:7511",
"content-type": "application/json",
"content-length": "515"
},
"content": {
"some-scalar-param": "scalar-value",
"myfile":{
"filename":"myfile.png",
"encoding":"7bit",
"mimetype":"image/png",
"file":"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAAAAAA6fptVAAAACklEQVQI12P4DwABAQEAG7buVgAAAABJRU5ErkJggg==" …
```
=> Http multipart/form-data support to enable file uploads

lib/service/HttpProxy.js, test/service/httpProxy.test.js
* Adds a new check to detect stringified Buffer in raw HTTP responses, in order to convert them back to a Buffer object before sending the payload back to the client (fix #49)
* As the code to convert result content has grown over time, it has been isolated in a separate function, making `sendRequest` more readable
=> Fix #49: incorrect stringified Buffer detection in raw responses

docker-compose/dev.yml, docker-compose/scripts/run-dev.sh, lib/core/KuzzleProxy.js, lib/plugins/package.js, lib/service/Backend.js, lib/service/Broker.js, package.json
Add debug mode in kuzzle-proxy for `plugins`, `backend` and `broker` (should be extended)
```shell
export NODE_ENV=development
export DEBUG=kuzzle-proxy:*
export DEBUG=kuzzle-proxy:plugins
export DEBUG=kuzzle-proxy:plugins,kuzzle-proxy:broker
pm2 restart all
```
*see more usages here: https://www.npmjs.com/package/debug#wildcards*
* kuzzle-proxy:plugins
* kuzzle-proxy:broker
* kuzzle-proxy:backend
Added a docker-compose file for development mode with file change watcher
=> Develop add debug mode

.proxyrc.sample, lib/core/config.js, lib/service/HttpProxy.js, lib/service/protocol/SocketIo.js, lib/service/protocol/Websocket.js, test/service/httpProxy.test.js, test/service/protocol/socketIo.test.js, test/service/protocol/websocket.test.js
Since the merge of ports for all 3 core protocols, it's better now to setup the `host` and `port` settings in the config's root instead of the HTTP related config.
Also move `maxRequestSize` to root config and use it within websocket and socketio protocols
=> Improve protocol settings + use requestMaxSize for all protocols

package.json, test/core/kuzzleProxy.test.js
Bluebird was only used by one obsolete line in unit tests. It has been removed.
=> Remove unused bluebird dependency

lib/service/Router.js, test/service/router.test.js
This PR fixes the case where an error issued by the proxy would be eventually be received as an empty string by the client.
* #62 
Errors are always embedded inside a [`RequestResponse`](https://github.com/kuzzleio/kuzzle-common-objects/blob/master/lib/models/requestResponse.js) object. In case the error is triggered by Kuzzle, the `response` object has already been serialized during the transport of the message from Kuzzle to the proxy.
This serialization process was not done when the error was directly issued by the proxy, and because the [`RequestResponse`](https://github.com/kuzzleio/kuzzle-common-objects/blob/master/lib/models/requestResponse.js) native object does not actually have any `content` property, the end result would be an empty string.
=> fixes #62 - empty errors coming from proxy

lib/service/HttpProxy.js, test/service/httpProxy.test.js
When an HTTP request is errored it was never removed from `clientConnectionStore`
This result with a bad behavior: each request will be resend to backend when a new registration is done (HTTP connection is already ended)
=> Fix http client connection leak

docker-compose/dev.yml
This PR adds `ptrace` rights to Kuzzle containers, allowing `gcore` to attach itself to a running process and to produce a core dump.
This solves the `ptrace: Operation not permitted` error when running a kuzzle dump from a docker container, running on Ubuntu 14.10 and newer.
This should not affect security since recent kernels have also Yama with ptrace protection, meaning that a process must explicitly provide the rights to `gcore` to attach itself to it, which is done by the [dumpme module](https://github.com/kuzzleio/dumpme).
Docker unconditionnally applies a default AppArmor configuration, confining containers. A bug in older AppArmor versions (installed on Ubuntu Trusty by default) prevented Docker to apply confinement rules on `ptrace` calls for this version of Ubuntu.
AppArmor has …
=> allow ptrace to be run from a kuzzle container

lib/service/Backend.js, lib/service/Broker.js, test/service/backend.test.js
This PR adds support for the new `shutdown` signal, sent by Kuzzle nodes when they are about to shut themselves down.
This signal instructs the proxy to remove the node from the backend list, without invalidating requests registered on it. The remaining requests, if any, are invalidated and cleaned up only when the associated socket closes or ends up in an error state.
https://github.com/kuzzleio/kuzzle/issues/816
=> Add support for Kuzzle graceful shutdown

lib/core/KuzzleProxy.js
=> Filter volatile instead of metadata in access logs

lib/core/KuzzleProxy.js, lib/service/Backend.js, lib/service/Broker.js, lib/service/ProxyBackendHandler.js, test/core/kuzzleProxy.test.js, test/service/backend.test.js, test/service/broker.test.js, test/service/proxyBackendHandler.test.js
:warning: **MERGE ONLY WHITH ITS [COUNTERPART ON KUZZLE](https://github.com/kuzzleio/kuzzle/pull/842)!!**
This PR fixes a situation, partly leading to situations described in https://github.com/kuzzleio/kuzzle/issues/836.
The main change introduced is that the proxy now waits for Kuzzle to be ready before sending its initial state (client connections) and accepting receiving incoming requests.
=> Fix client connections not being sent to Kuzzle

lib/core/KuzzleProxy.js, lib/service/Backend.js, lib/service/Broker.js, lib/service/ProxyBackendHandler.js, test/core/kuzzleProxy.test.js, test/service/backend.test.js, test/service/broker.test.js, test/service/proxyBackendHandler.test.js
:warning: **MERGE ONLY WITH ITS [KUZZLE COUNTERPART](https://github.com/kuzzleio/kuzzle/pull/842)**
:information_source: This PR is a copy of https://github.com/kuzzleio/kuzzle-proxy/pull/73, which was accidently merged (already approved)
This PR partly fixes some unhandled exceptions on client disconnections (cf https://github.com/kuzzleio/kuzzle/issues/836)
Notably, this PR now waits for Kuzzle to be ready before sending it the clients list (prevents some cases where some `subscribe`/`join` actions could be received _after_ a disconnection occurs.
=> Fix 836 ghost rooms

lib/service/protocol/SocketIo.js, lib/service/protocol/Websocket.js, package.json, test/service/protocol/socketIo.test.js, test/service/protocol/websocket.test.js
Add request headers (coming from HTTP handshake headers) to the request.context for both Websocket and SocketIO protocols (headers are already transmitted to Kuzzle for HTTP protocol)
This will enable kuzzle to handle restrictions according to some headers values.
fix #76
=> Add request headers to request.context

lib/core/Context.js, lib/service/Router.js, lib/service/protocol/SocketIo.js, lib/service/protocol/Websocket.js, package.json, test/core/context.test.js, test/service/protocol/socketIo.test.js, test/service/protocol/websocket.test.js, test/service/router.test.js
fix #78 
From: 
`execute(request, callback)`
to:
`execute({payload, connectionId, protocol, headers}, callback)`
(with the `headers` property being optional)
With the `router.execute` change above, protocol plugins should not need this constructor anymore.
This way, it won't be in conflict with the current `pluginContext.constructors.Request` constructor in Kuzzle Core, taking a `Request` instance as its first argument, which is impossible to do in Kuzzle Proxy.
=> Change the router.execute plugin accessor to allow protocols to inject headers

lib/core/KuzzleProxy.js, lib/service/Backend.js, lib/service/Broker.js, lib/service/ProxyBackendHandler.js, lib/service/Router.js, lib/service/protocol/Websocket.js, package-lock.json, package.json, test/service/backend.test.js, test/service/broker.test.js, test/service/protocol/socketIo.test.js, test/service/protocol/websocket.test.js, test/service/router.test.js
This PR applies some fixes required to enable running a cluster of Kuzzle instance in a sticky session mode.
@TBC
* remove unused packages
* upgrade dependencies => implies a small breaking change with ws, where the `upgradeReq` property has been removed from the socket object, hence the related code
* package-lock.json file committed (created by npm@5)
=> Allow sticky mode for cluster

lib/service/Backend.js, lib/service/Broker.js, lib/service/protocol/SocketIo.js, lib/service/protocol/Websocket.js, test/service/backend.test.js, test/service/broker.test.js, test/service/protocol/socketIo.test.js, test/service/protocol/websocket.test.js, test/service/router.test.js
- When no backend are left, disconnect active client connection with error message
- When no backend are left and a new connection is established, refuse it
- Websocket request from Socket.IO were also managed by Websocket protocol 
- Removed useless logs in proxy output
=> Close client connection when no backend left

lib/service/Backend.js, lib/service/ProxyBackendHandler.js, test/service/backend.test.js, test/service/proxyBackendHandler.test.js
It will avoid the proxy to infinite loop btw 2 registered backends who automatically try to reconnect.
=> Deny to activate a new backend if another one is already active.

.github/issue_template.md, .github/pull_request_template.md, .travis.yml, Dockerfile, build-docker-images.sh, docker-compose/dev.yml, docker-compose/scripts/run-dev.sh, docker-compose/scripts/run-test.sh, package-lock.json, test/travis-bin/run-tests.sh
This PR use the new `core-dev` container to run the test suite against Node8 and Node6.  
The proxy image also use Node8. The image is built with a multi-stage build.  
This image is build with Travis and no longer with Dockerhub automated build.
- Step 1 : Run tests `sh test/travis-bin/run-tests.sh
- Step 1 : Run docker-compose `docker-compose -f docker-compose/dev.yml up`
- Add PR/issue template
=> Add test against node8 and node6
